services:
  - type: web
    name: sistema-ncm
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 120
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
